node {
  stage ('Checkout') {
    checkout scm
    sh 'pwd'
    sh 'chmod a+x ./biketracks/gradlew'
  }

  stage ('Build') {
    sh './gradlew clean assemble'
  }

  stage ('Unit tests') {
    sh './gradlew app:test --info'
  }

  stage ('Publish') {
  }
}
